### ISSUE TITLE
cmd npm run WARNING

### ISSUE THREAD

**Issue by bhswallow** [thirdweb-example/cra-javascript-starter#2]
C:\Users\Administrator>node -v
v14.19.1

C:\Users\Administrator>npm -v
8.6.0

C:\Users\Administrator>create-react-app --version
5.0.1

-------------------------------------------------------------------------
npm run

WARNING in ./node_modules/@metamask/safe-event-emitter/index.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'F:\web\cra-javascript-starter\node_modules\@metamask\safe-event-emitter\index.ts' file: Error: ENOENT: no such file or directory, open 'F:\web\cra-javascript-starter\node_modules\@metamask\safe-event-emitter\index.ts'
 @ ./node_modules/@coinbase/wallet-sdk/dist/provider/CoinbaseWalletProvider.js 15:45-84
 @ ./node_modules/@coinbase/wallet-sdk/dist/index.js 11:33-77 22:31-75
 @ ./node_modules/wagmi-core/connectors/coinbaseWallet/dist/wagmi-core-connectors-coinbaseWallet.esm.js 3:0-57 117:47-64
 @ ./node_modules/wagmi/connectors/coinbaseWallet/dist/wagmi-connectors-coinbaseWallet.esm.js 1:0-79 1:0-79
 @ ./node_modules/@thirdweb-dev/react/dist/index.js 42614:9-51
 @ ./src/index.js 8:0-64 11:22-37 13:33-49

WARNING in ./node_modules/@thirdweb-dev/react/dist/index.js 39772:47-54
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./src/index.js 8:0-64 11:22-37 13:33-49

WARNING in ./node_modules/@thirdweb-dev/react/dist/index.js 39775:37-44
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./src/index.js 8:0-64 11:22-37 13:33-49

WARNING in ./node_modules/@walletconnect/browser-utils/dist/esm/browser.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'F:\web\cra-javascript-starter\node_modules\@walletconnect\browser-utils\src\browser.ts' file: Error: ENOENT: no such file or directory, open 'F:\web\cra-javascript-starter\node_modules\@walletconnect\browser-utils\src\browser.ts'
 @ ./node_modules/@walletconnect/browser-utils/dist/esm/index.js 1:0-26 1:0-26
 @ ./node_modules/@walletconnect/utils/dist/esm/index.js 1:0-45 1:0-45
 @ ./node_modules/@walletconnect/ethereum-provider/dist/esm/index.js 4:0-65 58:8-31 126:19-28
 @ ./node_modules/wagmi-core/connectors/walletConnect/dist/wagmi-core-connectors-walletConnect.esm.js 3:0-69 119:102-123
 @ ./node_modules/wagmi/connectors/walletConnect/dist/wagmi-connectors-walletConnect.esm.js 1:0-77 1:0-77
 @ ./node_modules/@thirdweb-dev/react/dist/index.js 42616:9-50
 @ ./src/index.js 8:0-64 11:22-37 13:33-49

WARNING in ./node_modules/@walletconnect/browser-utils/dist/esm/index.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'F:\web\cra-javascript-starter\node_modules\@walletconnect\browser-utils\src\index.ts' file: Error: ENOENT: no such file or directory, open 'F:\web\cra-javascript-starter\node_modules\@walletconnect\browser-utils\src\index.ts'
 @ ./node_modules/@walletconnect/utils/dist/esm/index.js 1:0-45 1:0-45
 @ ./node_modules/@walletconnect/ethereum-provider/dist/esm/index.js 4:0-65 58:8-31 126:19-28
 @ ./node_modules/wagmi-core/connectors/walletConnect/dist/wagmi-core-connectors-walletConnect.esm.js 3:0-69 119:102-123
 @ ./node_modules/wagmi/connectors/walletConnect/dist/wagmi-connectors-walletConnect.esm.js 1:0-77 1:0-77
 @ ./node_modules/@thirdweb-dev/react/dist/index.js 42616:9-50
 @ ./src/index.js 8:0-64 11:22-37 13:33-49

WARNING in ./node_modules/@walletconnect/browser-utils/dist/esm/json.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'F:\web\cra-javascript-starter\node_modules\@walletconnect\browser-utils\src\json.ts' file: Error: ENOENT: no such file or directory, open 'F:\web\cra-javascript-starter\node_modules\@walletconnect\browser-utils\src\json.ts'
 @ ./node_modules/@walletconnect/browser-utils/dist/esm/index.js 2:0-23 2:0-23
 @ ./node_modules/@walletconnect/utils/dist/esm/index.js 1:0-45 1:0-45
 @ ./node_modules/@walletconnect/ethereum-provider/dist/esm/index.js 4:0-65 58:8-31 126:19-28
 @ ./node_modules/wagmi-core/connectors/walletConnect/dist/wagmi-core-connectors-walletConnect.esm.js 3:0-69 119:102-123
 @ ./node_modules/wagmi/connectors/walletConnect/dist/wagmi-connectors-walletConnect.esm.js 1:0-77 1:0-77
 @ ./node_modules/@thirdweb-dev/react/dist/index.js 42616:9-50
 @ ./src/index.js 8:0-64 11:22-37 13:33-49

WARNING in ./node_modules/@walletconnect/browser-utils/dist/esm/local.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'F:\web\cra-javascript-starter\node_modules\@walletconnect\browser-utils\src\local.ts' file: Error: ENOENT: no such file or directory, open 'F:\web\cra-javascript-starter\node_modules\@walletconnect\browser-utils\src\local.ts'
 @ ./node_modules/@walletconnect/browser-utils/dist/esm/index.js 3:0-24 3:0-24
 @ ./node_modules/@walletconnect/utils/dist/esm/index.js 1:0-45 1:0-45
 @ ./node_modules/@walletconnect/ethereum-provider/dist/esm/index.js 4:0-65 58:8-31 126:19-28
 @ ./node_modules/wagmi-core/connectors/walletConnect/dist/wagmi-core-connectors-walletConnect.esm.js 3:0-69 119:102-123
 @ ./node_modules/wagmi/connectors/walletConnect/dist/wagmi-connectors-walletConnect.esm.js 1:0-77 1:0-77
 @ ./node_modules/@thirdweb-dev/react/dist/index.js 42616:9-50
 @ ./src/index.js 8:0-64 11:22-37 13:33-49

WARNING in ./node_modules/@walletconnect/browser-utils/dist/esm/mobile.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'F:\web\cra-javascript-starter\node_modules\@walletconnect\browser-utils\src\mobile.ts' file: Error: ENOENT: no such file or directory, open 'F:\web\cra-javascript-starter\node_modules\@walletconnect\browser-utils\src\mobile.ts'
 @ ./node_modules/@walletconnect/browser-utils/dist/esm/index.js 4:0-25 4:0-25
 @ ./node_modules/@walletconnect/utils/dist/esm/index.js 1:0-45 1:0-45
 @ ./node_modules/@walletconnect/ethereum-provider/dist/esm/index.js 4:0-65 58:8-31 126:19-28
 @ ./node_modules/wagmi-core/connectors/walletConnect/dist/wagmi-core-connectors-walletConnect.esm.js 3:0-69 119:102-123
 @ ./node_modules/wagmi/connectors/walletConnect/dist/wagmi-connectors-walletConnect.esm.js 1:0-77 1:0-77
 @ ./node_modules/@thirdweb-dev/react/dist/index.js 42616:9-50
 @ ./src/index.js 8:0-64 11:22-37 13:33-49

WARNING in ./node_modules/@walletconnect/browser-utils/dist/esm/registry.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'F:\web\cra-javascript-starter\node_modules\@walletconnect\browser-utils\src\registry.ts' file: Error: ENOENT: no such file or directory, open 'F:\web\cra-javascript-starter\node_modules\@walletconnect\browser-utils\src\registry.ts'
 @ ./node_modules/@walletconnect/browser-utils/dist/esm/index.js 5:0-27 5:0-27
 @ ./node_modules/@walletconnect/utils/dist/esm/index.js 1:0-45 1:0-45
 @ ./node_modules/@walletconnect/ethereum-provider/dist/esm/index.js 4:0-65 58:8-31 126:19-28
 @ ./node_modules/wagmi-core/connectors/walletConnect/dist/wagmi-core-connectors-walletConnect.esm.js 3:0-69 119:102-123
 @ ./node_modules/wagmi/connectors/walletConnect/dist/wagmi-connectors-walletConnect.esm.js 1:0-77 1:0-77
 @ ./node_modules/@thirdweb-dev/react/dist/index.js 42616:9-50
 @ ./src/index.js 8:0-64 11:22-37 13:33-49
...

WARNING in ./node_modules/json-rpc-engine/dist/getUniqueId.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'F:\web\cra-javascript-starter\node_modules\json-rpc-engine\src\getUniqueId.ts' file: Error: ENOENT: no such file or directory, open 'F:\web\cra-javascript-starter\node_modules\json-rpc-engine\src\getUniqueId.ts'
 @ ./node_modules/json-rpc-engine/dist/index.js 30:13-37
 @ ./node_modules/eth-json-rpc-filters/subscriptionManager.js 7:4-30 @ ./node_modules/@coinbase/wallet-sdk/dist/provider/SubscriptionManager.js 10:34-85
 @ ./node_modules/@coinbase/wallet-sdk/dist/provider/CoinbaseWalletProvider.js 35:30-62
 @ ./node_modules/@coinbase/wallet-sdk/dist/index.js 11:33-77 22:31-75
 @ ./node_modules/wagmi-core/connectors/coinbaseWallet/dist/wagmi-core-connectors-coinbaseWallet.esm.js 3:0-57 117:47-64
 @ ./node_modules/wagmi/connectors/coinbaseWallet/dist/wagmi-connectors-coinbaseWallet.esm.js 1:0-79 1:0-79
 @ ./node_modules/@thirdweb-dev/react/dist/index.js 42614:9-51
 @ ./src/index.js 8:0-64 11:22-37 13:33-49

WARNING in ./node_modules/json-rpc-engine/dist/idRemapMiddleware.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'F:\web\cra-javascript-starter\node_modules\json-rpc-engine\src\idRemapMiddleware.ts' file: Error: ENOENT: no such file or directory, open 'F:\web\cra-javascript-starter\node_modules\json-rpc-engine\src\idRemapMiddleware.ts'
 @ ./node_modules/json-rpc-engine/dist/index.js 24:13-43
 @ ./node_modules/eth-json-rpc-filters/subscriptionManager.js 7:4-30 @ ./node_modules/@coinbase/wallet-sdk/dist/provider/SubscriptionManager.js 10:34-85
 @ ./node_modules/@coinbase/wallet-sdk/dist/provider/CoinbaseWalletProvider.js 35:30-62
 @ ./node_modules/@coinbase/wallet-sdk/dist/index.js 11:33-77 22:31-75
 @ ./node_modules/wagmi-core/connectors/coinbaseWallet/dist/wagmi-core-connectors-coinbaseWallet.esm.js 3:0-57 117:47-64
 @ ./node_modules/wagmi/connectors/coinbaseWallet/dist/wagmi-connectors-coinbaseWallet.esm.js 1:0-79 1:0-79
 @ ./node_modules/@thirdweb-dev/react/dist/index.js 42614:9-51
 @ ./src/index.js 8:0-64 11:22-37 13:33-49

WARNING in ./node_modules/json-rpc-engine/dist/index.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'F:\web\cra-javascript-starter\node_modules\json-rpc-engine\src\index.ts' file: Error: ENOENT: no such file or directory, open 'F:\web\cra-javascript-starter\node_modules\json-rpc-engine\src\index.ts'
 @ ./node_modules/eth-json-rpc-filters/subscriptionManager.js 7:4-30 @ ./node_modules/@coinbase/wallet-sdk/dist/provider/SubscriptionManager.js 10:34-85
 @ ./node_modules/@coinbase/wallet-sdk/dist/provider/CoinbaseWalletProvider.js 35:30-62
 @ ./node_modules/@coinbase/wallet-sdk/dist/index.js 11:33-77 22:31-75
 @ ./node_modules/wagmi-core/connectors/coinbaseWallet/dist/wagmi-core-connectors-coinbaseWallet.esm.js 3:0-57 117:47-64
 @ ./node_modules/wagmi/connectors/coinbaseWallet/dist/wagmi-connectors-coinbaseWallet.esm.js 1:0-79 1:0-79
 @ ./node_modules/@thirdweb-dev/react/dist/index.js 42614:9-51
 @ ./src/index.js 8:0-64 11:22-37 13:33-49

WARNING in ./node_modules/json-rpc-engine/dist/mergeMiddleware.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'F:\web\cra-javascript-starter\node_modules\json-rpc-engine\src\mergeMiddleware.ts' file: Error: ENOENT: no such file or directory, open 'F:\web\cra-javascript-starter\node_modules\json-rpc-engine\src\mergeMiddleware.ts'
 @ ./node_modules/json-rpc-engine/dist/index.js 34:13-41
 @ ./node_modules/eth-json-rpc-filters/subscriptionManager.js 7:4-30 @ ./node_modules/@coinbase/wallet-sdk/dist/provider/SubscriptionManager.js 10:34-85
 @ ./node_modules/@coinbase/wallet-sdk/dist/provider/CoinbaseWalletProvider.js 35:30-62
 @ ./node_modules/@coinbase/wallet-sdk/dist/index.js 11:33-77 22:31-75
 @ ./node_modules/wagmi-core/connectors/coinbaseWallet/dist/wagmi-core-connectors-coinbaseWallet.esm.js 3:0-57 117:47-64
 @ ./node_modules/wagmi/connectors/coinbaseWallet/dist/wagmi-connectors-coinbaseWallet.esm.js 1:0-79 1:0-79
 @ ./node_modules/@thirdweb-dev/react/dist/index.js 42614:9-51
 @ ./src/index.js 8:0-64 11:22-37 13:33-49

83 warnings have detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

webpack 5.72.1 compiled with 83 warnings in 24030 ms

**Comment by PeachieDude** [comment]
Same here, did solve some by getting files from [https://github.com/MetaMask](https://github.com/MetaMask) but theres lots missing

Failed to parse source map from '/home/peachiedude/tssw/node_modules/@metamask/safe-event-emitter/index.ts' file: Error: ENOENT: no such file or directory, open '/home/peachiedude/tssw/node_modules/@metamask/safe-event-emitter/index.ts'

Failed to parse source map from '/home/peachiedude/tssw/node_modules/@walletconnect/browser-utils/src/browser.ts' file: Error: ENOENT: no such file or directory, open '/home/peachiedude/tssw/node_modules/@walletconnect/browser-utils/src/browser.ts'

Failed to parse source map from '/home/peachiedude/tssw/node_modules/@walletconnect/browser-utils/src/index.ts' file: Error: ENOENT: no such file or directory, open '/home/peachiedude/tssw/node_modules/@walletconnect/browser-utils/src/index.ts'

Failed to parse source map from '/home/peachiedude/tssw/node_modules/@walletconnect/browser-utils/src/json.ts' file: Error: ENOENT: no such file or directory, open '/home/peachiedude/tssw/node_modules/@walletconnect/browser-utils/src/json.ts'

Failed to parse source map from '/home/peachiedude/tssw/node_modules/@walletconnect/browser-utils/src/local.ts' file: Error: ENOENT: no such file or directory, open '/home/peachiedude/tssw/node_modules/@walletconnect/browser-utils/src/local.ts'

Failed to parse source map from '/home/peachiedude/tssw/node_modules/@walletconnect/browser-utils/src/mobile.ts' file: Error: ENOENT: no such file or directory, open '/home/peachiedude/tssw/node_modules/@walletconnect/browser-utils/src/mobile.ts'

Failed to parse source map from '/home/peachiedude/tssw/node_modules/@walletconnect/browser-utils/src/registry.ts' file: Error: ENOENT: no such file or directory, open '/home/peachiedude/tssw/node_modules/@walletconnect/browser-utils/src/registry.ts'

Failed to parse source map from '/home/peachiedude/tssw/node_modules/@walletconnect/core/src/errors.ts' file: Error: ENOENT: no such file or directory, open '/home/peachiedude/tssw/node_modules/@walletconnect/core/src/errors.ts'

Failed to parse source map from '/home/peachiedude/tssw/node_modules/@walletconnect/core/src/events.ts' file: Error: ENOENT: no such file or directory, open '/home/peachiedude/tssw/node_modules/@walletconnect/core/src/events.ts'

Failed to parse source map from '/home/peachiedude/tssw/node_modules/@walletconnect/core/src/storage.ts' file: Error: ENOENT: no such file or directory, open '/home/peachiedude/tssw/node_modules/@walletconnect/core/src/storage.ts'

Failed to parse source map from '/home/peachiedude/tssw/node_modules/@walletconnect/core/src/url.ts' file: Error: ENOENT: no such file or directory, open '/home/peachiedude/tssw/node_modules/@walletconnect/core/src/url.ts'

Failed to parse source map from '/home/peachiedude/tssw/node_modules/@walletconnect/crypto/src/browser/aes.ts' file: Error: ENOENT: no such file or directory, open '/home/peachiedude/tssw/node_modules/@walletconnect/crypto/src/browser/aes.ts'

Failed to parse source map from '/home/peachiedude/tssw/node_modules/@walletconnect/crypto/src/browser/hmac.ts' file: Error: ENOENT: no such file or directory, open '/home/peachiedude/tssw/node_modules/@walletconnect/crypto/src/browser/hmac.ts'

Failed to parse source map from '/home/peachiedude/tssw/node_modules/@walletconnect/crypto/src/browser/index.ts' file: Error: ENOENT: no such file or directory, open '/home/peachiedude/tssw/node_modules/@walletconnect/crypto/src/browser/index.ts'

Failed to parse source map from '/home/peachiedude/tssw/node_modules/@walletconnect/crypto/src/browser/sha2.ts' file: Error: ENOENT: no such file or directory, open '/home/peachiedude/tssw/node_modules/@walletconnect/crypto/src/browser/sha2.ts'

Failed to parse source map from '/home/peachiedude/tssw/node_modules/@walletconnect/crypto/src/constants/default.ts' file: Error: ENOENT: no such file or directory, open '/home/peachiedude/tssw/node_modules/@walletconnect/crypto/src/constants/default.ts'

Failed to parse source map from '/home/peachiedude/tssw/node_modules/@walletconnect/crypto/src/constants/encoding.ts' file: Error: ENOENT: no such file or directory, open '/home/peachiedude/tssw/node_modules/@walletconnect/crypto/src/constants/encoding.ts'

Failed to parse source map from '/home/peachiedude/tssw/node_modules/@walletconnect/crypto/src/constants/error.ts' file: Error: ENOENT: no such file or directory, open '/home/peachiedude/tssw/node_modules/@walletconnect/crypto/src/constants/error.ts'

Failed to parse source map from '/home/peachiedude/tssw/node_modules/@walletconnect/crypto/src/constants/index.ts' file: Error: ENOENT: no such file or directory, open '/home/peachiedude/tssw/node_modules/@walletconnect/crypto/src/constants/index.ts'

Failed to parse source map from '/home/peachiedude/tssw/node_modules/@walletconnect/crypto/src/constants/length.ts' file: Error: ENOENT: no such file or directory, open '/home/peachiedude/tssw/node_modules/@walletconnect/crypto/src/constants/length.ts'

Failed to parse source map from '/home/peachiedude/tssw/node_modules/@walletconnect/crypto/src/constants/operations.ts' file: Error: ENOENT: no such file or directory, open '/home/peachiedude/tssw/node_modules/@walletconnect/crypto/src/constants/operations.ts'

Failed to parse source map from '/home/peachiedude/tssw/node_modules/@walletconnect/crypto/src/helpers/env.ts' file: Error: ENOENT: no such file or directory, open '/home/peachiedude/tssw/node_modules/@walletconnect/crypto/src/helpers/env.ts'

Failed to parse source map from '/home/peachiedude/tssw/node_modules/@walletconnect/crypto/src/helpers/index.ts' file: Error: ENOENT: no such file or directory, open '/home/peachiedude/tssw/node_modules/@walletconnect/crypto/src/helpers/index.ts'

Failed to parse source map from '/home/peachiedude/tssw/node_modules/@walletconnect/crypto/src/helpers/pkcs7.ts' file: Error: ENOENT: no such file or directory, open '/home/peachiedude/tssw/node_modules/@walletconnect/crypto/src/helpers/pkcs7.ts'

Failed to parse source map from '/home/peachiedude/tssw/node_modules/@walletconnect/crypto/src/helpers/types.ts' file: Error: ENOENT: no such file or directory, open '/home/peachiedude/tssw/node_modules/@walletconnect/crypto/src/helpers/types.ts'

Failed to parse source map from '/home/peachiedude/tssw/node_modules/@walletconnect/crypto/src/helpers/validators.ts' file: Error: ENOENT: no such file or directory, open '/home/peachiedude/tssw/node_modules/@walletconnect/crypto/src/helpers/validators.ts'

Failed to parse source map from '/home/peachiedude/tssw/node_modules/@walletconnect/crypto/src/lib/browser.ts' file: Error: ENOENT: no such file or directory, open '/home/peachiedude/tssw/node_modules/@walletconnect/crypto/src/lib/browser.ts'

Failed to parse source map from '/home/peachiedude/tssw/node_modules/@walletconnect/iso-crypto/src/index.ts' file: Error: ENOENT: no such file or directory, open '/home/peachiedude/tssw/node_modules/@walletconnect/iso-crypto/src/index.ts'

Failed to parse source map from '/home/peachiedude/tssw/node_modules/@walletconnect/jsonrpc-http-connection/src/http.ts' file: Error: ENOENT: no such file or directory, open '/home/peachiedude/tssw/node_modules/@walletconnect/jsonrpc-http-connection/src/http.ts'

Failed to parse source map from '/home/peachiedude/tssw/node_modules/@walletconnect/jsonrpc-http-connection/src/index.ts' file: Error: ENOENT: no such file or directory, open '/home/peachiedude/tssw/node_modules/@walletconnect/jsonrpc-http-connection/src/index.ts'

Failed to parse source map from '/home/peachiedude/tssw/node_modules/@walletconnect/jsonrpc-provider/src/index.ts' file: Error: ENOENT: no such file or directory, open '/home/peachiedude/tssw/node_modules/@walletconnect/jsonrpc-provider/src/index.ts'

Failed to parse source map from '/home/peachiedude/tssw/node_modules/@walletconnect/jsonrpc-provider/src/provider.ts' file: Error: ENOENT: no such file or directory, open '/home/peachiedude/tssw/node_modules/@walletconnect/jsonrpc-provider/src/provider.ts'

Failed to parse source map from '/home/peachiedude/tssw/node_modules/@walletconnect/jsonrpc-types/src/index.ts' file: Error: ENOENT: no such file or directory, open '/home/peachiedude/tssw/node_modules/@walletconnect/jsonrpc-types/src/index.ts'

Failed to parse source map from '/home/peachiedude/tssw/node_modules/@walletconnect/jsonrpc-types/src/jsonrpc.ts' file: Error: ENOENT: no such file or directory, open '/home/peachiedude/tssw/node_modules/@walletconnect/jsonrpc-types/src/jsonrpc.ts'

Failed to parse source map from '/home/peachiedude/tssw/node_modules/@walletconnect/jsonrpc-types/src/misc.ts' file: Error: ENOENT: no such file or directory, open '/home/peachiedude/tssw/node_modules/@walletconnect/jsonrpc-types/src/misc.ts'

Failed to parse source map from '/home/peachiedude/tssw/node_modules/@walletconnect/jsonrpc-types/src/provider.ts' file: Error: ENOENT: no such file or directory, open '/home/peachiedude/tssw/node_modules/@walletconnect/jsonrpc-types/src/provider.ts'

Failed to parse source map from '/home/peachiedude/tssw/node_modules/@walletconnect/jsonrpc-types/src/validator.ts' file: Error: ENOENT: no such file or directory, open '/home/peachiedude/tssw/node_modules/@walletconnect/jsonrpc-types/src/validator.ts'

Failed to parse source map from '/home/peachiedude/tssw/node_modules/@walletconnect/jsonrpc-utils/src/constants.ts' file: Error: ENOENT: no such file or directory, open '/home/peachiedude/tssw/node_modules/@walletconnect/jsonrpc-utils/src/constants.ts'

Failed to parse source map from '/home/peachiedude/tssw/node_modules/@walletconnect/jsonrpc-utils/src/env.ts' file: Error: ENOENT: no such file or directory, open '/home/peachiedude/tssw/node_modules/@walletconnect/jsonrpc-utils/src/env.ts'

Failed to parse source map from '/home/peachiedude/tssw/node_modules/@walletconnect/jsonrpc-utils/src/error.ts' file: Error: ENOENT: no such file or directory, open '/home/peachiedude/tssw/node_modules/@walletconnect/jsonrpc-utils/src/error.ts'

Failed to parse source map from '/home/peachiedude/tssw/node_modules/@walletconnect/jsonrpc-utils/src/format.ts' file: Error: ENOENT: no such file or directory, open '/home/peachiedude/tssw/node_modules/@walletconnect/jsonrpc-utils/src/format.ts'

Failed to parse source map from '/home/peachiedude/tssw/node_modules/@walletconnect/jsonrpc-utils/src/index.ts' file: Error: ENOENT: no such file or directory, open '/home/peachiedude/tssw/node_modules/@walletconnect/jsonrpc-utils/src/index.ts'

Failed to parse source map from '/home/peachiedude/tssw/node_modules/@walletconnect/jsonrpc-utils/src/routing.ts' file: Error: ENOENT: no such file or directory, open '/home/peachiedude/tssw/node_modules/@walletconnect/jsonrpc-utils/src/routing.ts'

Failed to parse source map from '/home/peachiedude/tssw/node_modules/@walletconnect/jsonrpc-utils/src/types.ts' file: Error: ENOENT: no such file or directory, open '/home/peachiedude/tssw/node_modules/@walletconnect/jsonrpc-utils/src/types.ts'

Failed to parse source map from '/home/peachiedude/tssw/node_modules/@walletconnect/jsonrpc-utils/src/url.ts' file: Error: ENOENT: no such file or directory, open '/home/peachiedude/tssw/node_modules/@walletconnect/jsonrpc-utils/src/url.ts'

Failed to parse source map from '/home/peachiedude/tssw/node_modules/@walletconnect/jsonrpc-utils/src/validators.ts' file: Error: ENOENT: no such file or directory, open '/home/peachiedude/tssw/node_modules/@walletconnect/jsonrpc-utils/src/validators.ts'

Failed to parse source map from '/home/peachiedude/tssw/node_modules/@walletconnect/randombytes/src/browser/index.ts' file: Error: ENOENT: no such file or directory, open '/home/peachiedude/tssw/node_modules/@walletconnect/randombytes/src/browser/index.ts'

Failed to parse source map from '/home/peachiedude/tssw/node_modules/@walletconnect/socket-transport/src/index.ts' file: Error: ENOENT: no such file or directory, open '/home/peachiedude/tssw/node_modules/@walletconnect/socket-transport/src/index.ts'

Failed to parse source map from '/home/peachiedude/tssw/node_modules/@walletconnect/socket-transport/src/network.ts' file: Error: ENOENT: no such file or directory, open '/home/peachiedude/tssw/node_modules/@walletconnect/socket-transport/src/network.ts'

Failed to parse source map from '/home/peachiedude/tssw/node_modules/@walletconnect/utils/src/constants.ts' file: Error: ENOENT: no such file or directory, open '/home/peachiedude/tssw/node_modules/@walletconnect/utils/src/constants.ts'

Failed to parse source map from '/home/peachiedude/tssw/node_modules/@walletconnect/utils/src/encoding.ts' file: Error: ENOENT: no such file or directory, open '/home/peachiedude/tssw/node_modules/@walletconnect/utils/src/encoding.ts'

Failed to parse source map from '/home/peachiedude/tssw/node_modules/@walletconnect/utils/src/ethereum.ts' file: Error: ENOENT: no such file or directory, open '/home/peachiedude/tssw/node_modules/@walletconnect/utils/src/ethereum.ts'

Failed to parse source map from '/home/peachiedude/tssw/node_modules/@walletconnect/utils/src/payload.ts' file: Error: ENOENT: no such file or directory, open '/home/peachiedude/tssw/node_modules/@walletconnect/utils/src/payload.ts'

Failed to parse source map from '/home/peachiedude/tssw/node_modules/@walletconnect/utils/src/session.ts' file: Error: ENOENT: no such file or directory, open '/home/peachiedude/tssw/node_modules/@walletconnect/utils/src/session.ts'

Failed to parse source map from '/home/peachiedude/tssw/node_modules/@walletconnect/utils/src/url.ts' file: Error: ENOENT: no such file or directory, open '/home/peachiedude/tssw/node_modules/@walletconnect/utils/src/url.ts'

**Comment by jarrodwatts** [comment]
Unfortunately this is an ongoing problem with Create React App.

You can find some ways to hide the errors in their thread below, but this is out of our control sadly

https://github.com/facebook/create-react-app/pull/11752

**Comment by PeachieDude** [comment]
> Unfortunately this is an ongoing problem with Create React App.
> 
> You can find some ways to hide the errors in their thread below, but this is out of our control sadly
> 
> [facebook/create-react-app#11752](https://github.com/facebook/create-react-app/pull/11752)

Sad to see that this is your best answer.
At the start on my comment i said that there's some ways to workaround at least some part of the problem.. and for that, maintaining a git isn't just "sorry I can't do a thing about it"
You could contact the other part and try to solve the problem..
Even more when it comes to a serious work as you guys are doing and bringing to the community..

Maybe it isn't that important/serious as you guys are trying to show.

**Comment by jarrodwatts** [comment]
@PeachieDude 

We're currently working on v3 of our React SDK coming in the next few weeks, which will help address the warnings in this issue. As these current warnings don't prevent development, you're still able to use this repo which is why I've closed it.

An example solution that works well to hide the warnings for me is using this https://github.com/mswjs/msw/issues/1030#issuecomment-1009253387 

Feel free to contribute to the repo if you find anything else you like in particular that resolves it differently.

Alternatively, we have [Vite ](https://github.com/thirdweb-example/vite-javascript-starter) and [Nextjs](https://github.com/thirdweb-example/next-javascript-starter) examples that don't have this issue
