### ISSUE TITLE
Create-React-App v5+ Broken

### ISSUE THREAD

**Issue by rbrisita** [thirdweb-example/cra-javascript-starter#3]
Running `npm start` or `yarn start` both create this error:

```shell
ERROR in ./node_modules/@zag-js/react/dist/index.mjs 6:0-71
Module not found: Error: Can't resolve 'use-sync-external-store/shim' in '~\thirdweb-app-js\node_modules\@zag-js\react\dist'
Did you mean 'index.js'?
BREAKING CHANGE: The request 'use-sync-external-store/shim' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
```

Projects were created using these commands:
* `npx thirdweb create --app --cra --js`
* `npx thirdweb create --template cra-javascript-starter`

`Package.json` contains:
```json
  "dependencies": {
    "@testing-library/jest-dom": "^5.16.4",
    "@testing-library/react": "^13.2.0",
    "@testing-library/user-event": "^14.2.0",
    "@thirdweb-dev/react": "^2",
    "@thirdweb-dev/sdk": "^2",
    "ethers": "^5.6.8",
    "react": "^18.1.0",
    "react-dom": "^18.1.0",
    "react-scripts": "^5.0.1",
    "web-vitals": "^2.1.4"
  },
  "devDependencies": {
    "assert": "^2.0.0",
    "stream": "^0.0.2"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
```

CLI versions:
thirdweb-cli `v0.7.3`
Node `v16.14.2`
NPM `v8.5.0`

**Comment by rbrisita** [comment]
This has to do with `create-react-app` v5+ as webpack no longer supports polyfills. For whatever reason, installing the previous version (v4.0.3) regardless if global or not, results in this display:

```shell
You are running `create-react-app` 4.0.3, which is behind the latest release (5.0.1).

We no longer support global installation of Create React App.
```

🙄🤷

This link: https://github.com/ChainSafe/web3.js#web3-and-create-react-app gives some insight on resolving it.
Here are the steps to install the needed polyfills, constructing the `config-overrides.js`, and modifying `packgage.json` so that the example can compile and display:

## Install
`npm install --save-dev stream-browserify assert use-sync-external-store react-app-rewired`

## Files
### config-overrides.js
```js
const webpack = require('webpack');

module.exports = function override(config) {
    const fallback = config.resolve.fallback || {};
    Object.assign(fallback, {
        "stream": require.resolve("stream-browserify"),
        "use-sync-external-store/shim": require.resolve("use-sync-external-store/shim"),
    })
    config.resolve.fallback = fallback;
    config.ignoreWarnings = [/Failed to parse source map/];
    return config;
}
```

### `package.json`
```json
  "scripts": {
    "start": " react-app-rewired start",
    "build": " react-app-rewired build",
    "test": " react-app-rewired test",
    "eject": "react-scripts eject"
  },
```

**Comment by jarrodwatts** [comment]
Thanks a lot for the detailed information @rbrisita!

We're working on fixing these problems in our React SDK itself right now, and then introducing some tests in our new [JS Monorepo](https://github.com/thirdweb-dev/js) so this doesn't happen again.

I'll leave this ticket open for now as this is great for users running into this issue - thank you!
